name: book-list-CI

on:
   push:
     branches: [main]
   pull_request:
     branches: [main]

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-ci
  cancel-in-progress: true

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']
        poetry-version: ['1.7']
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{matrix.poetry-version}}
      - name: Install Dependencies using Poetry
        run: poetry install
      - name: Formatting with black
        run: poetry run black --check .
      - name: Sort imports with isort
        run: poetry run isort --check-only --diff .
      - name: Lint with flake8
        run: poetry run flake8 .
